class SeedClients < ActiveRecord::Migration
  def up
    Client.create(:name => "Lastname Firstname", :phone => "Phone 1", :email => "Email", :business_id => 2 )
    Client.create(:name => " Beth Hall", :phone => "0416205667", :email => "Bettythebrave@hotmail.com", :business_id => 2 )
    Client.create(:name => " Eva", :phone => "0409134963", :email => "eva@petaloudar.com.au", :business_id => 2 )
    Client.create(:name => " Bateup Penny", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "A Amanda", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "A Angela ", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "a Basia", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "A Chelsea", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "A Justine ", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "A Lucas", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "A Manlai", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "A Molly", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "a Natasha", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "a Nikita", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "aldrice Zoe", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "allardice zoe", :phone => "0430504058", :email => "", :business_id => 2 )
    Client.create(:name => "Anderson Belinda", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Annesley Maria", :phone => "0418145849", :email => "maria.annesley@gmail.com", :business_id => 2 )
    Client.create(:name => "Archibald Lisa", :phone => "0400639142", :email => "", :business_id => 2 )
    Client.create(:name => "B Eva", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "B Victoria", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Bagdadi Renee", :phone => "0466006416", :email => "renee.bagdadi@pfizer.com", :business_id => 2 )
    Client.create(:name => "Barker Kate", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Bateup Penny", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Bird Natasha", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Blackman Paul", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Bone Lucy", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "brodie diane", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Brown Alicia", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Buego Ruby", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Burber Victoria", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "bywater russell", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "C Carmel", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Caddaye Adrian", :phone => "0413209690", :email => "adrian.caddaye@exponet.au", :business_id => 2 )
    Client.create(:name => "Carman Kate", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "carmen kate", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Chindamo Anna", :phone => "0413 370 029", :email => "acorpaci@yahoo.com.au", :business_id => 2 )
    Client.create(:name => "Collins Rebecca", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Cooper Jason", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Cooper Rebecca ", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Crow Penny", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "cunningham erin", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "De lean Sarah ", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Demasi Marielle", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Dimasi Marielle", :phone => "0407150901", :email => "marielle.bright@gmail.com", :business_id => 2 )
    Client.create(:name => "e barsia", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "E Leeanne", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Ede Bernadette", :phone => "0400115925", :email => "dettede@gmail.com", :business_id => 2 )
    Client.create(:name => "Eggenhuizen Leeann", :phone => "0411 833 855", :email => "leeann.eggenhuizen@gmail.com", :business_id => 2 )
    Client.create(:name => "Ella Watson", :phone => "0407566730", :email => "ej_watto@hotmail.com", :business_id => 2 )
    Client.create(:name => "Eng Natalie", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "eng natalie", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Faulkner Helen", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Ferris Rebecca", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Fitzpatrick Rozlyn", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Flynn Sam ", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Forde Leneen", :phone => "96082243", :email => "l.forde@cornwalls.com.au", :business_id => 2 )
    Client.create(:name => "furness andrea", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "furness andy", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "go dolly", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Gustofson Sarah", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "H Hh", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Hain Sarah", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "healey amanda", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Hopwood Brett", :phone => "0418877108", :email => "hopwood.brett@gmail.com", :business_id => 2 )
    Client.create(:name => "ingram miranda", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Jackson Debora", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Johns Jillian", :phone => "0415050941", :email => "jillian.alice.j@gmail.com", :business_id => 2 )
    Client.create(:name => "Johnson Isabel", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Johnson Mardi", :phone => "0466 748 545", :email => "mjohnson07@optusnet.com.au", :business_id => 2 )
    Client.create(:name => "Jones Natalie", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Kane Rachel ", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Koko Estelle", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Kranenbroek Fiona", :phone => "0404534831", :email => "fiona.kranenbroek@yahoo.com.au", :business_id => 2 )
    Client.create(:name => "l Laura", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "l nijole", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "lagerwey Jessica", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Lee Jennifer", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Lee Michelle", :phone => "0434016814", :email => "Rmts.lee@optusnet.com.au", :business_id => 2 )
    Client.create(:name => "Lloyd julian ", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "lucinskaite nijole", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "M Darren", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "M Mona", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "madan judith", :phone => "94866843", :email => "", :business_id => 2 )
    Client.create(:name => "Madan Sunita", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Mahoney Aphra", :phone => "0406785708", :email => "aphra_mahon@hotmail.com", :business_id => 2 )
    Client.create(:name => "Mathieson Clare", :phone => "0412288710", :email => "clarelmathieson@gmail.com", :business_id => 2 )
    Client.create(:name => "Mathison Clare", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "matthews seth & lisa", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "McGrane Caitlin", :phone => "0448816750", :email => "mcgrane.caitlin@gmail.com", :business_id => 2 )
    Client.create(:name => "Meredith Ainslee", :phone => "0430840443", :email => "ainslee.meredith@gmail.com", :business_id => 2 )
    Client.create(:name => "Moio Clare", :phone => "0449753113", :email => "claremoio@fastmail.fm", :business_id => 2 )
    Client.create(:name => "Morris Melissa", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "mullens fran", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "noble amanda", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "o'brien denise", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "O'Halloran Ashleigh", :phone => "", :email => "a.ohalloran@live.com", :business_id => 2 )
    Client.create(:name => "ogden nisha", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Ohalloran Ash", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "p eva", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "p Hailey", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "P Helen", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "P Jana", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "P Paul", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "p Victoria", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "papastamatopoulos Helen", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Patrakis Helen", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Patrakos Helen", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Patroni Kathleen", :phone => "0407662524", :email => "klpat2@student.monash.edu", :business_id => 2 )
    Client.create(:name => "Pepe Daniella", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Periga Anna ", :phone => "0403263764", :email => "", :business_id => 2 )
    Client.create(:name => "petch nick", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Ppp Victoria", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Proctor Michelle", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Reed Emily", :phone => "0439760604", :email => "", :business_id => 2 )
    Client.create(:name => "reid emily", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Reid NiccI", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "richardson sheena", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Room Eva", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Room Healing", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Room Lisa", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Sakko Maggie", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Sako Maggie", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "sarah meeting", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Scarmozzino Maria", :phone => "0407459619", :email => "rosie_scar@hotmail.com", :business_id => 2 )
    Client.create(:name => "Shelford Laura", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Smith Bacara", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "taddeo tina", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "tardy Erinn", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Tattio Tina", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Taylor Rachel", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "test signup Test signup", :phone => "1300859600", :email => "troy.sawtell@sponsoredlinx.com", :business_id => 2 )
    Client.create(:name => "tovorovic Danijella", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Tucca Leah", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Van Wilsem Hannah", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Walker Brett", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Ward Darren", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Watson Ella", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "welsh Katie", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "wilsem hannah", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Wolsley Brooke", :phone => "0401163021", :email => "superwoolz@hotmail.com", :business_id => 2 )
    Client.create(:name => "Wright Carolyn Eva", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "yee karryn", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Yee Karyn", :phone => "0410885523", :email => "karynamelia@gmail.com", :business_id => 2 )
    Client.create(:name => "Z Clementine", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "zawadzki clementine", :phone => "0431453390", :email => "", :business_id => 2 )
    Client.create(:name => "Zawaska Clementine", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "zerafa Chelsea", :phone => "", :email => "", :business_id => 2 )

  end

  def down
  end
end
