class SeedClients < ActiveRecord::Migration
  def up
    Client.create(:name => "Firstname Lastname", :phone => "Phone 1", :email => "Email", :business_id => 2 )
    Client.create(:name => "Beth Hall ", :phone => "0416205667", :email => "Bettythebrave@hotmail.com", :business_id => 2 )
    Client.create(:name => "Eva ", :phone => "0409134963", :email => "eva@petaloudar.com.au", :business_id => 2 )
    Client.create(:name => "Penny  Bateup", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Amanda A", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Angela  A", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Basia a", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Chelsea A", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Justine  A", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Lucas A", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Manlai A", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Molly A", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Natasha a", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Nikita a", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Zoe aldrice", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "zoe allardice", :phone => "0430504058", :email => "", :business_id => 2 )
    Client.create(:name => "Belinda Anderson", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Maria Annesley", :phone => "0418145849", :email => "maria.annesley@gmail.com", :business_id => 2 )
    Client.create(:name => "Lisa Archibald", :phone => "0400639142", :email => "", :business_id => 2 )
    Client.create(:name => "Eva B", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Victoria B", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Renee Bagdadi", :phone => "0466006416", :email => "renee.bagdadi@pfizer.com", :business_id => 2 )
    Client.create(:name => "Kate Barker", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Penny Bateup", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Natasha Bird", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Paul Blackman", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Lucy Bone", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "diane brodie", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Alicia Brown", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Ruby Buego", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Victoria Burber", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "russell bywater", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Carmel C", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Adrian Caddaye", :phone => "0413209690", :email => "adrian.caddaye@exponet.au", :business_id => 2 )
    Client.create(:name => "Kate Carman", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "kate carmen", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Anna Chindamo", :phone => "0413 370 029", :email => "acorpaci@yahoo.com.au", :business_id => 2 )
    Client.create(:name => "Rebecca Collins", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Jason Cooper", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Rebecca  Cooper", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Penny Crow", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "erin cunningham", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Sarah  De lean", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Marielle Demasi", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Marielle Dimasi", :phone => "0407150901", :email => "marielle.bright@gmail.com", :business_id => 2 )
    Client.create(:name => "barsia e", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Leeanne E", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Bernadette Ede", :phone => "0400115925", :email => "dettede@gmail.com", :business_id => 2 )
    Client.create(:name => "Leeann Eggenhuizen", :phone => "0411 833 855", :email => "leeann.eggenhuizen@gmail.com", :business_id => 2 )
    Client.create(:name => "Watson Ella", :phone => "0407566730", :email => "ej_watto@hotmail.com", :business_id => 2 )
    Client.create(:name => "Natalie Eng", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "natalie eng", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Helen Faulkner", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Rebecca Ferris", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Rozlyn Fitzpatrick", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Sam  Flynn", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Leneen Forde", :phone => "96082243", :email => "l.forde@cornwalls.com.au", :business_id => 2 )
    Client.create(:name => "andrea furness", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "andy furness", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "dolly go", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Sarah Gustofson", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Hh H", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Sarah Hain", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "amanda healey", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Brett Hopwood", :phone => "0418877108", :email => "hopwood.brett@gmail.com", :business_id => 2 )
    Client.create(:name => "miranda ingram", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Debora Jackson", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Jillian Johns", :phone => "0415050941", :email => "jillian.alice.j@gmail.com", :business_id => 2 )
    Client.create(:name => "Isabel Johnson", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Mardi Johnson", :phone => "0466 748 545", :email => "mjohnson07@optusnet.com.au", :business_id => 2 )
    Client.create(:name => "Natalie Jones", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Rachel  Kane", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Estelle Koko", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Fiona Kranenbroek", :phone => "0404534831", :email => "fiona.kranenbroek@yahoo.com.au", :business_id => 2 )
    Client.create(:name => "Laura l", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "nijole l", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Jessica lagerwey", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Jennifer Lee", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Michelle Lee", :phone => "0434016814", :email => "Rmts.lee@optusnet.com.au", :business_id => 2 )
    Client.create(:name => "julian  Lloyd", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "nijole lucinskaite", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Darren M", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Mona M", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "judith madan", :phone => "94866843", :email => "", :business_id => 2 )
    Client.create(:name => "Sunita Madan", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Aphra Mahoney", :phone => "0406785708", :email => "aphra_mahon@hotmail.com", :business_id => 2 )
    Client.create(:name => "Clare Mathieson", :phone => "0412288710", :email => "clarelmathieson@gmail.com", :business_id => 2 )
    Client.create(:name => "Clare Mathison", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "seth & lisa matthews", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Caitlin McGrane", :phone => "0448816750", :email => "mcgrane.caitlin@gmail.com", :business_id => 2 )
    Client.create(:name => "Ainslee Meredith", :phone => "0430840443", :email => "ainslee.meredith@gmail.com", :business_id => 2 )
    Client.create(:name => "Clare Moio", :phone => "0449753113", :email => "claremoio@fastmail.fm", :business_id => 2 )
    Client.create(:name => "Melissa Morris", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Fran Mullens", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Amanda Noble", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Denise O'brien", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Ashleigh O'Halloran", :phone => "", :email => "a.ohalloran@live.com", :business_id => 2 )
    Client.create(:name => "nisha ogden", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Ash Ohalloran", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "eva p", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Hailey p", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Helen P", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Jana P", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Paul P", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Victoria p", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Helen papastamatopoulos", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Helen Patrakis", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Helen Patrakos", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Kathleen Patroni", :phone => "0407662524", :email => "klpat2@student.monash.edu", :business_id => 2 )
    Client.create(:name => "Daniella Pepe", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Anna  Periga", :phone => "0403263764", :email => "", :business_id => 2 )
    Client.create(:name => "nick petch", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Victoria Ppp", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Michelle Proctor", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Emily Reed", :phone => "0439760604", :email => "", :business_id => 2 )
    Client.create(:name => "emily reid", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "NiccI Reid", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "sheena richardson", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Eva Room", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Healing Room", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Lisa Room", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Maggie Sakko", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Maggie Sako", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "meeting sarah", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Maria Scarmozzino", :phone => "0407459619", :email => "rosie_scar@hotmail.com", :business_id => 2 )
    Client.create(:name => "Laura Shelford", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Bacara Smith", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "tina taddeo", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Erinn tardy", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Tina Tattio", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Rachel Taylor", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Test signup test signup", :phone => "1300859600", :email => "troy.sawtell@sponsoredlinx.com", :business_id => 2 )
    Client.create(:name => "Danijella tovorovic", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Leah Tucca", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Hannah Van Wilsem", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Brett Walker", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Darren Ward", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Ella Watson", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Katie welsh", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "hannah wilsem", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Brooke Wolsley", :phone => "0401163021", :email => "superwoolz@hotmail.com", :business_id => 2 )
    Client.create(:name => "Carolyn Eva Wright", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "karryn yee", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Karyn Yee", :phone => "0410885523", :email => "karynamelia@gmail.com", :business_id => 2 )
    Client.create(:name => "Clementine Z", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "clementine zawadzki", :phone => "0431453390", :email => "", :business_id => 2 )
    Client.create(:name => "Clementine Zawaska", :phone => "", :email => "", :business_id => 2 )
    Client.create(:name => "Chelsea zerafa", :phone => "", :email => "", :business_id => 2 )

  end

  def down
  end
end
